import type { Metadata } from 'next'
import './globals.css'
import { Header } from '@/components/header'
import { register } from 'swiper/element-bundle'
import 'swiper/css'
import 'swiper/css/navigation'
import 'swiper/css/pagination'
import 'swiper/css/scrollbar'

register()

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="h-screen">
        <Header />
        {children}
      </body>
    </html>
  )
}
